language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: Qbov7gMj41NQif8+R+j+xOarIJivIVzIwoXus/pfgAOJ/5ycz65h2CZWnPoPxksZWnWcWY/AUlRw6GNSaE/8tgdKAvAVpVqXl72R+W5rnLm1It9Z3q0uYEEzI3UuzzFyJyDc8vwIH/D8iIKZZCYc21p8UEuHDuoRMYOrcZF5oHM=
  - secure: KzovArMIau0m+q7wTC7CarJyzOsvNZErn4Ng7UUQYFUISzqt8xTOssMLV7ykp1l9Vjoxg5LjR4WFSVujEF27nZS60idIjuctdl41LIhxHZEgVVTgnHi8hkwd5ffkA0UgETt89h7TQzOwlUuD+/nsaE7CVUr2W3gxj8PR8Fvsbwk=

before_install:
- npm install -g grunt-cli

before_script:
- git submodule update --init --recursive

install:
- npm install

script:
- grunt --stack travis
